import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './navbar'
import Footer from './footer'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NEXTICA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="hr">
      {/* <body className={inter.className}>{children}</body> */}
      <Navbar />
      <main>{children}</main>
      <Footer />
    </html>
  );
}
